"use client";

import {
  Activity,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Clock,
  CreditCard,
  Factory,
  FileText,
  FolderTree,
  Globe,
  Image as ImageIcon,
  KeyRound,
  Landmark,
  LayoutDashboard,
  AlertTriangle,
  Package,
  Palette,
  Plug,
  Puzzle,
  RefreshCw,
  ScrollText,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Store,
  Tags,
  Truck,
  UserCog,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Clock,
  CreditCard,
  Factory,
  FileText,
  FolderTree,
  Globe,
  Image: ImageIcon,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Package,
  Palette,
  Plug,
  Puzzle,
  RefreshCw,
  ScrollText,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Store,
  Tags,
  Truck,
  UserCog,
  Users,
};

export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? LayoutDashboard;
  return <Icon className={className} aria-hidden="true" />;
}
