import "server-only";
import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { S3Client, DeleteObjectCommand, GetObjectCommand, HeadObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { env, storageDriver } from "@/lib/env";
import { AppError } from "@/lib/errors";

/**
 * Object storage abstraction.
 *
 * Two interchangeable drivers implement the same contract:
 *
 *  - `s3`     — any S3-compatible bucket (AWS, Cloudflare R2, Backblaze B2, MinIO).
 *               Browsers receive presigned PUT/GET URLs, never credentials.
 *  - `local`  — objects on the server's disk behind signed, expiring URLs served by
 *               `/api/v1/media/storage/upload|download`. Same guarantees (no credentials
 *               in the browser, time-limited access), test/development only.
 *  - `disabled` — every operation fails with an actionable error instead of silently
 *               pretending the upload worked.
 *
 * Nothing above this file knows which driver is in use, so switching storage providers
 * is a configuration change.
 */

export interface UploadTarget {
  /** URL the browser PUTs the file to. */
  url: string;
  method: "PUT";
  headers: Record<string, string>;
  /** Absolute URL that can be stored on a public asset (public visibility only). */
  publicUrl: string | null;
  expiresAt: Date;
}

export interface ObjectHead {
  exists: boolean;
  sizeBytes: number;
  contentType: string | null;
}

export interface SignedDownload {
  url: string;
  expiresAt: Date;
}

const SIGNING_CONTEXT = "media-url-v1";

/** Key used to sign local-driver URLs. Derived, never equal to the raw app secret. */
function signingKey(): Buffer {
  return createHash("sha256").update(`${SIGNING_CONTEXT}:${env().APP_ENCRYPTION_KEY}`).digest();
}

function signedToken(payload: string): string {
  return createHmac("sha256", signingKey()).update(payload).digest("base64url");
}

export function verifyLocalSignature(payload: string, token: string): boolean {
  const expected = Buffer.from(signedToken(payload));
  const provided = Buffer.from(token);
  if (expected.length !== provided.length) return false;
  return timingSafeEqual(expected, provided);
}

/** Build the local-driver URL for an operation, including its expiry and signature. */
export function localStorageUrl(input: {
  operation: "upload" | "download";
  key: string;
  expiresAt: Date;
  contentType?: string;
  sizeBytes?: number;
  downloadName?: string;
  disposition?: "inline" | "attachment";
}): string {
  const base = env().APP_URL.replace(/\/$/, "");
  const url = new URL(`${base}/api/v1/media/storage/${input.operation}`);
  url.searchParams.set("key", input.key);
  url.searchParams.set("expires", String(Math.floor(input.expiresAt.getTime() / 1000)));
  if (input.contentType) url.searchParams.set("contentType", input.contentType);
  if (input.sizeBytes !== undefined) url.searchParams.set("size", String(input.sizeBytes));
  if (input.downloadName) url.searchParams.set("name", input.downloadName);
  if (input.disposition) url.searchParams.set("disposition", input.disposition);
  const payload = url.searchParams.toString();
  url.searchParams.set("signature", signedToken(payload));
  // Relative URLs work behind reverse proxies and never point a remote browser at localhost.
  return `${url.pathname}${url.search}`;
}

export function localStoragePath(key: string): string {
  // Keys are generated by the application, but the guard keeps a hostile key from
  // escaping the configured directory even if one ever arrives from outside.
  if (!/^[A-Za-z0-9._/-]+$/.test(key) || key.includes("..")) {
    throw AppError.validation("Invalid storage key");
  }
  const root = path.resolve(process.cwd(), env().LOCAL_STORAGE_DIR);
  const full = path.resolve(root, key);
  if (!full.startsWith(root + path.sep)) throw AppError.validation("Invalid storage key");
  return full;
}

// ------------------------------------------------------------------ s3 driver

let s3Client: S3Client | null = null;

function s3(): S3Client {
  const config = env();
  if (!config.S3_BUCKET) throw AppError.integration("Object storage is not configured (S3_BUCKET is missing)");
  if (!s3Client) {
    s3Client = new S3Client({
      region: config.S3_REGION,
      // Do not presign the SDK default CRC32 of an empty, not-yet-supplied body.
      requestChecksumCalculation: "WHEN_REQUIRED",
      ...(config.S3_ENDPOINT ? { endpoint: config.S3_ENDPOINT } : {}),
      forcePathStyle: config.S3_FORCE_PATH_STYLE ?? false,
      ...(config.S3_ACCESS_KEY_ID && config.S3_SECRET_ACCESS_KEY
        ? { credentials: { accessKeyId: config.S3_ACCESS_KEY_ID, secretAccessKey: config.S3_SECRET_ACCESS_KEY } }
        : {}),
    });
  }
  return s3Client;
}

function publicUrlFor(key: string): string | null {
  const base = env().S3_PUBLIC_BASE_URL;
  return base ? `${base.replace(/\/$/, "")}/${key}` : null;
}

// --------------------------------------------------------------- public API

export function storageDriverName(): "s3" | "local" | "disabled" {
  return storageDriver();
}

export function storageIsConfigured(): boolean {
  return storageDriver() !== "disabled";
}

/** A URL the browser can PUT a file to, valid for a short window. */
export async function createUploadTarget(input: {
  key: string;
  contentType: string;
  sizeBytes?: number;
  expiresInSeconds?: number;
}): Promise<UploadTarget> {
  const expiresIn = input.expiresInSeconds ?? env().S3_PRESIGN_EXPIRES_SECONDS;
  const expiresAt = new Date(Date.now() + expiresIn * 1000);
  const driver = storageDriver();

  if (driver === "disabled") {
    throw AppError.integration("Media storage is not configured on this deployment");
  }

  if (driver === "s3") {
    // Bind the declared length and prevent overwrites; confirmation also checks actual bytes.
    const url = await getSignedUrl(
      s3(),
      new PutObjectCommand({ Bucket: env().S3_BUCKET!, Key: input.key, ContentType: input.contentType, ContentLength: input.sizeBytes, IfNoneMatch: "*" }),
      { expiresIn },
    );
    return { url, method: "PUT", headers: { "content-type": input.contentType, "if-none-match": "*" }, publicUrl: publicUrlFor(input.key), expiresAt };
  }

  return {
    url: localStorageUrl({ operation: "upload", key: input.key, expiresAt, contentType: input.contentType, sizeBytes: input.sizeBytes }),
    method: "PUT",
    headers: { "content-type": input.contentType, "if-none-match": "*" },
    publicUrl: null,
    expiresAt,
  };
}

/** A time-limited URL for reading an object (used for private media). */
export async function createDownloadUrl(input: {
  key: string;
  expiresInSeconds?: number;
  downloadName?: string;
  disposition?: "inline" | "attachment";
}): Promise<SignedDownload> {
  const expiresIn = input.expiresInSeconds ?? env().S3_PRESIGN_EXPIRES_SECONDS;
  const expiresAt = new Date(Date.now() + expiresIn * 1000);
  const driver = storageDriver();

  if (driver === "disabled") throw AppError.integration("Media storage is not configured on this deployment");

  if (driver === "s3") {
    const url = await getSignedUrl(
      s3(),
      new GetObjectCommand({
        Bucket: env().S3_BUCKET!,
        Key: input.key,
        ...(input.disposition ? { ResponseContentDisposition: `${input.disposition}; filename="${input.downloadName ?? "file"}"` } : {}),
      }),
      { expiresIn },
    );
    return { url, expiresAt };
  }

  return {
    url: localStorageUrl({
      operation: "download",
      key: input.key,
      expiresAt,
      downloadName: input.downloadName,
      disposition: input.disposition,
    }),
    expiresAt,
  };
}

/** Read object metadata (used to verify an upload completed as declared). */
export async function headObject(key: string): Promise<ObjectHead> {
  const driver = storageDriver();
  if (driver === "disabled") return { exists: false, sizeBytes: 0, contentType: null };

  if (driver === "s3") {
    try {
      const result = await s3().send(new HeadObjectCommand({ Bucket: env().S3_BUCKET!, Key: key }));
      return { exists: true, sizeBytes: Number(result.ContentLength ?? 0), contentType: result.ContentType ?? null };
    } catch (error) {
      if ((error as { $metadata?: { httpStatusCode?: number } }).$metadata?.httpStatusCode !== 404) throw error;
      return { exists: false, sizeBytes: 0, contentType: null };
    }
  }

  try {
    const info = await stat(localStoragePath(key));
    return { exists: info.isFile(), sizeBytes: info.size, contentType: null };
  } catch {
    return { exists: false, sizeBytes: 0, contentType: null };
  }
}

/** Read an object into memory: only for small images (dimension probing, copies). */
export async function getObject(key: string, maxBytes = 25 * 1024 * 1024): Promise<Buffer> {
  const head = await headObject(key);
  if (!head.exists) throw AppError.notFound("The media file is missing from storage");
  if (head.sizeBytes > maxBytes) throw AppError.validation("This file is too large to read inline");

  if (storageDriver() === "s3") {
    const result = await s3().send(new GetObjectCommand({ Bucket: env().S3_BUCKET!, Key: key }));
    const body = await result.Body?.transformToByteArray();
    if (!body) throw AppError.notFound("The media file is missing from storage");
    return Buffer.from(body);
  }

  return readFile(localStoragePath(key));
}

/** Write an object from the server (fixtures, generated thumbnails, test uploads). */
export async function putObject(input: { key: string; body: Buffer | Uint8Array; contentType: string }): Promise<void> {
  const driver = storageDriver();
  if (driver === "disabled") throw AppError.integration("Media storage is not configured on this deployment");

  if (driver === "s3") {
    await s3().send(new PutObjectCommand({ Bucket: env().S3_BUCKET!, Key: input.key, Body: input.body, ContentType: input.contentType }));
    return;
  }

  const full = localStoragePath(input.key);
  await mkdir(path.dirname(full), { recursive: true });
  await writeFile(full, input.body);
}

export async function deleteObject(key: string): Promise<void> {
  const driver = storageDriver();
  if (driver === "disabled") throw AppError.integration("Media storage is not configured on this deployment");

  if (driver === "s3") {
    await s3().send(new DeleteObjectCommand({ Bucket: env().S3_BUCKET!, Key: key }));
    return;
  }

  await rm(localStoragePath(key), { force: true });
}
