import type { Metadata } from "next";
import Link from "next/link";
import { prisma } from "@/lib/db/client";
import { requireSession } from "@/lib/auth/session";
import { assertPermission } from "@/lib/permissions";
import { parseListQuery } from "@/lib/validation";
import { formatRelative } from "@/lib/utils";
import { Badge, Card, CardContent, EmptyState, PageHeader } from "@/components/ui/primitives";
import { SubmitButton } from "@/components/ui/interactive";
import { Pagination } from "@/components/ui/pagination";
import { markAllNotificationsReadAction, markNotificationReadAction, markNotificationUnreadAction } from "@/modules/notifications/actions";

export const metadata: Metadata = { title: "Notifications" };
export const dynamic = "force-dynamic";

const SEVERITY_VARIANT: Record<string, "info" | "success" | "warning" | "danger"> = {
  INFO: "info",
  SUCCESS: "success",
  WARNING: "warning",
  CRITICAL: "danger",
};

export default async function NotificationsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const session = await requireSession();
  assertPermission(session, "notification.view");
  const params = await searchParams;
  const query = parseListQuery(params, { defaultSortBy: "createdAt" });
  const onlyUnread = params.filter === "unread";

  const where = {
    userId: session.id,
    archivedAt: null,
    ...(onlyUnread ? { readAt: null } : {}),
  };

  const [recipients, total, unread] = await Promise.all([
    prisma.notificationRecipient.findMany({
      where,
      orderBy: { createdAt: "desc" },
      skip: query.skip,
      take: query.take,
      include: {
        notification: {
          select: {
            id: true,
            title: true,
            body: true,
            severity: true,
            type: true,
            url: true,
            entityType: true,
            entityId: true,
            createdAt: true,
          },
        },
      },
    }),
    prisma.notificationRecipient.count({ where }),
    prisma.notificationRecipient.count({ where: { userId: session.id, readAt: null, archivedAt: null } }),
  ]);

  return (
    <div className="space-y-4">
      <PageHeader
        title="Notifications"
        description={`${unread} unread notification${unread === 1 ? "" : "s"}. Notifications are generated by business events, never seeded with fake data.`}
        actions={
          <form action={markAllNotificationsReadAction}>
            <SubmitButton variant="outline" size="sm" pendingLabel="Marking…" disabled={unread === 0}>
              Mark all as read
            </SubmitButton>
          </form>
        }
      />

      <div className="flex gap-2 text-sm">
        <Link
          href="/admin/notifications"
          className={onlyUnread ? "text-slate-500 hover:underline" : "font-medium text-brand-600"}
        >
          All
        </Link>
        <span className="text-slate-300">|</span>
        <Link
          href="/admin/notifications?filter=unread"
          className={onlyUnread ? "font-medium text-brand-600" : "text-slate-500 hover:underline"}
        >
          Unread only
        </Link>
      </div>

      <Card>
        <CardContent className="space-y-2">
          {recipients.length === 0 ? (
            <EmptyState
              title={onlyUnread ? "No unread notifications" : "No notifications yet"}
              description="Low stock alerts, failed courier bookings, payment issues and job failures will appear here."
            />
          ) : (
            recipients.map((recipient) => {
              const notification = recipient.notification;
              return (
                <div
                  key={recipient.id}
                  className={`flex flex-wrap items-start justify-between gap-3 rounded-lg border p-3 ${
                    recipient.readAt ? "border-slate-200 bg-white" : "border-brand-200 bg-brand-50/40"
                  }`}
                >
                  <div className="min-w-0 space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge variant={SEVERITY_VARIANT[notification.severity] ?? "info"}>{notification.severity.toLowerCase()}</Badge>
                      <p className="font-medium text-slate-900">{notification.title}</p>
                      {recipient.readAt ? null : <span className="h-2 w-2 rounded-full bg-brand-600" aria-label="unread" />}
                    </div>
                    {notification.body ? <p className="text-sm text-slate-600">{notification.body}</p> : null}
                    <p className="text-xs text-slate-400">
                      {notification.type} · {formatRelative(notification.createdAt)}
                      {notification.entityType ? ` · ${notification.entityType}` : ""}
                    </p>
                  </div>
                  <div className="flex items-center gap-3 text-sm">
                    {notification.url ? (
                      <Link href={notification.url} className="font-medium text-brand-600 hover:underline">
                        Open
                      </Link>
                    ) : null}
                    {recipient.readAt ? (
                      <form action={markNotificationUnreadAction.bind(null, recipient.id)}>
                        <SubmitButton variant="ghost" size="sm" pendingLabel="…">
                          Mark unread
                        </SubmitButton>
                      </form>
                    ) : (
                      <form action={markNotificationReadAction.bind(null, recipient.id)}>
                        <SubmitButton variant="ghost" size="sm" pendingLabel="…">
                          Mark read
                        </SubmitButton>
                      </form>
                    )}
                  </div>
                </div>
              );
            })
          )}
        </CardContent>
        <div className="px-4">
          <Pagination page={query.page} pageSize={query.pageSize} total={total} basePath="/admin/notifications" searchParams={params} />
        </div>
      </Card>
    </div>
  );
}
