-- Generated by scripts/fk-check.mjs --emit-fix.
--
-- The initial migration created every foreign key with ON DELETE SET NULL, which
-- contradicts the referential actions declared in prisma/schema.prisma (and makes
-- deleting a parent fail outright when the column is NOT NULL). This migration
-- restores the declared behaviour for each affected constraint.
ALTER TABLE "BusinessSetting" DROP CONSTRAINT "BusinessSetting_businessId_fkey";
ALTER TABLE "BusinessSetting" ADD CONSTRAINT "BusinessSetting_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "User" DROP CONSTRAINT "User_businessId_fkey";
ALTER TABLE "User" ADD CONSTRAINT "User_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Role" DROP CONSTRAINT "Role_businessId_fkey";
ALTER TABLE "Role" ADD CONSTRAINT "Role_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "RolePermission" DROP CONSTRAINT "RolePermission_roleId_fkey";
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "RolePermission" DROP CONSTRAINT "RolePermission_permissionId_fkey";
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "UserRole" DROP CONSTRAINT "UserRole_userId_fkey";
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "UserRole" DROP CONSTRAINT "UserRole_roleId_fkey";
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Session" DROP CONSTRAINT "Session_userId_fkey";
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CustomerSession" DROP CONSTRAINT "CustomerSession_customerId_fkey";
ALTER TABLE "CustomerSession" ADD CONSTRAINT "CustomerSession_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PasswordResetToken" DROP CONSTRAINT "PasswordResetToken_userId_fkey";
ALTER TABLE "PasswordResetToken" ADD CONSTRAINT "PasswordResetToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VerificationCode" DROP CONSTRAINT "VerificationCode_customerId_fkey";
ALTER TABLE "VerificationCode" ADD CONSTRAINT "VerificationCode_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "IdempotencyRecord" DROP CONSTRAINT "IdempotencyRecord_businessId_fkey";
ALTER TABLE "IdempotencyRecord" ADD CONSTRAINT "IdempotencyRecord_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NumberSequence" DROP CONSTRAINT "NumberSequence_businessId_fkey";
ALTER TABLE "NumberSequence" ADD CONSTRAINT "NumberSequence_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Storefront" DROP CONSTRAINT "Storefront_businessId_fkey";
ALTER TABLE "Storefront" ADD CONSTRAINT "Storefront_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "StorefrontDomain" DROP CONSTRAINT "StorefrontDomain_storefrontId_fkey";
ALTER TABLE "StorefrontDomain" ADD CONSTRAINT "StorefrontDomain_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "StorefrontSetting" DROP CONSTRAINT "StorefrontSetting_storefrontId_fkey";
ALTER TABLE "StorefrontSetting" ADD CONSTRAINT "StorefrontSetting_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "DeliveryZone" DROP CONSTRAINT "DeliveryZone_businessId_fkey";
ALTER TABLE "DeliveryZone" ADD CONSTRAINT "DeliveryZone_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "DeliveryZone" DROP CONSTRAINT "DeliveryZone_storefrontId_fkey";
ALTER TABLE "DeliveryZone" ADD CONSTRAINT "DeliveryZone_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "DeliveryZone" DROP CONSTRAINT "DeliveryZone_districtCode_fkey";
ALTER TABLE "DeliveryZone" ADD CONSTRAINT "DeliveryZone_districtCode_fkey" FOREIGN KEY ("districtCode") REFERENCES "District" ("code") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "CheckoutFieldConfig" DROP CONSTRAINT "CheckoutFieldConfig_businessId_fkey";
ALTER TABLE "CheckoutFieldConfig" ADD CONSTRAINT "CheckoutFieldConfig_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ExchangeReason" DROP CONSTRAINT "ExchangeReason_businessId_fkey";
ALTER TABLE "ExchangeReason" ADD CONSTRAINT "ExchangeReason_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Category" DROP CONSTRAINT "Category_businessId_fkey";
ALTER TABLE "Category" ADD CONSTRAINT "Category_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Product" DROP CONSTRAINT "Product_businessId_fkey";
ALTER TABLE "Product" ADD CONSTRAINT "Product_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductCategory" DROP CONSTRAINT "ProductCategory_productId_fkey";
ALTER TABLE "ProductCategory" ADD CONSTRAINT "ProductCategory_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductCategory" DROP CONSTRAINT "ProductCategory_categoryId_fkey";
ALTER TABLE "ProductCategory" ADD CONSTRAINT "ProductCategory_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Attribute" DROP CONSTRAINT "Attribute_businessId_fkey";
ALTER TABLE "Attribute" ADD CONSTRAINT "Attribute_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "AttributeValue" DROP CONSTRAINT "AttributeValue_attributeId_fkey";
ALTER TABLE "AttributeValue" ADD CONSTRAINT "AttributeValue_attributeId_fkey" FOREIGN KEY ("attributeId") REFERENCES "Attribute" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductAttribute" DROP CONSTRAINT "ProductAttribute_productId_fkey";
ALTER TABLE "ProductAttribute" ADD CONSTRAINT "ProductAttribute_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductAttribute" DROP CONSTRAINT "ProductAttribute_attributeId_fkey";
ALTER TABLE "ProductAttribute" ADD CONSTRAINT "ProductAttribute_attributeId_fkey" FOREIGN KEY ("attributeId") REFERENCES "Attribute" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Variant" DROP CONSTRAINT "Variant_productId_fkey";
ALTER TABLE "Variant" ADD CONSTRAINT "Variant_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VariantAttributeValue" DROP CONSTRAINT "VariantAttributeValue_variantId_fkey";
ALTER TABLE "VariantAttributeValue" ADD CONSTRAINT "VariantAttributeValue_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VariantAttributeValue" DROP CONSTRAINT "VariantAttributeValue_attributeId_fkey";
ALTER TABLE "VariantAttributeValue" ADD CONSTRAINT "VariantAttributeValue_attributeId_fkey" FOREIGN KEY ("attributeId") REFERENCES "Attribute" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VariantAttributeValue" DROP CONSTRAINT "VariantAttributeValue_attributeValueId_fkey";
ALTER TABLE "VariantAttributeValue" ADD CONSTRAINT "VariantAttributeValue_attributeValueId_fkey" FOREIGN KEY ("attributeValueId") REFERENCES "AttributeValue" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductImage" DROP CONSTRAINT "ProductImage_productId_fkey";
ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductImage" DROP CONSTRAINT "ProductImage_mediaId_fkey";
ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "MediaAsset" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "VariantImage" DROP CONSTRAINT "VariantImage_variantId_fkey";
ALTER TABLE "VariantImage" ADD CONSTRAINT "VariantImage_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VariantImage" DROP CONSTRAINT "VariantImage_mediaId_fkey";
ALTER TABLE "VariantImage" ADD CONSTRAINT "VariantImage_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "MediaAsset" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PriceList" DROP CONSTRAINT "PriceList_businessId_fkey";
ALTER TABLE "PriceList" ADD CONSTRAINT "PriceList_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PriceList" DROP CONSTRAINT "PriceList_resellerId_fkey";
ALTER TABLE "PriceList" ADD CONSTRAINT "PriceList_resellerId_fkey" FOREIGN KEY ("resellerId") REFERENCES "Reseller" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PriceListItem" DROP CONSTRAINT "PriceListItem_priceListId_fkey";
ALTER TABLE "PriceListItem" ADD CONSTRAINT "PriceListItem_priceListId_fkey" FOREIGN KEY ("priceListId") REFERENCES "PriceList" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PriceListItem" DROP CONSTRAINT "PriceListItem_variantId_fkey";
ALTER TABLE "PriceListItem" ADD CONSTRAINT "PriceListItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Supplier" DROP CONSTRAINT "Supplier_businessId_fkey";
ALTER TABLE "Supplier" ADD CONSTRAINT "Supplier_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PurchaseOrder" DROP CONSTRAINT "PurchaseOrder_businessId_fkey";
ALTER TABLE "PurchaseOrder" ADD CONSTRAINT "PurchaseOrder_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PurchaseOrder" DROP CONSTRAINT "PurchaseOrder_supplierId_fkey";
ALTER TABLE "PurchaseOrder" ADD CONSTRAINT "PurchaseOrder_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PurchaseOrderItem" DROP CONSTRAINT "PurchaseOrderItem_purchaseOrderId_fkey";
ALTER TABLE "PurchaseOrderItem" ADD CONSTRAINT "PurchaseOrderItem_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PurchaseOrderItem" DROP CONSTRAINT "PurchaseOrderItem_variantId_fkey";
ALTER TABLE "PurchaseOrderItem" ADD CONSTRAINT "PurchaseOrderItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "GoodsReceipt" DROP CONSTRAINT "GoodsReceipt_purchaseOrderId_fkey";
ALTER TABLE "GoodsReceipt" ADD CONSTRAINT "GoodsReceipt_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "GoodsReceipt" DROP CONSTRAINT "GoodsReceipt_locationId_fkey";
ALTER TABLE "GoodsReceipt" ADD CONSTRAINT "GoodsReceipt_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "InventoryLocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "GoodsReceiptItem" DROP CONSTRAINT "GoodsReceiptItem_goodsReceiptId_fkey";
ALTER TABLE "GoodsReceiptItem" ADD CONSTRAINT "GoodsReceiptItem_goodsReceiptId_fkey" FOREIGN KEY ("goodsReceiptId") REFERENCES "GoodsReceipt" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "GoodsReceiptItem" DROP CONSTRAINT "GoodsReceiptItem_purchaseOrderItemId_fkey";
ALTER TABLE "GoodsReceiptItem" ADD CONSTRAINT "GoodsReceiptItem_purchaseOrderItemId_fkey" FOREIGN KEY ("purchaseOrderItemId") REFERENCES "PurchaseOrderItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PurchaseExpense" DROP CONSTRAINT "PurchaseExpense_purchaseOrderId_fkey";
ALTER TABLE "PurchaseExpense" ADD CONSTRAINT "PurchaseExpense_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PurchaseExpense" DROP CONSTRAINT "PurchaseExpense_goodsReceiptId_fkey";
ALTER TABLE "PurchaseExpense" ADD CONSTRAINT "PurchaseExpense_goodsReceiptId_fkey" FOREIGN KEY ("goodsReceiptId") REFERENCES "GoodsReceipt" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "InventoryLocation" DROP CONSTRAINT "InventoryLocation_businessId_fkey";
ALTER TABLE "InventoryLocation" ADD CONSTRAINT "InventoryLocation_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "InventoryBalance" DROP CONSTRAINT "InventoryBalance_locationId_fkey";
ALTER TABLE "InventoryBalance" ADD CONSTRAINT "InventoryBalance_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "InventoryLocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "InventoryBalance" DROP CONSTRAINT "InventoryBalance_variantId_fkey";
ALTER TABLE "InventoryBalance" ADD CONSTRAINT "InventoryBalance_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "InventoryMovement" DROP CONSTRAINT "InventoryMovement_businessId_fkey";
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "InventoryMovement" DROP CONSTRAINT "InventoryMovement_locationId_fkey";
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "InventoryLocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "InventoryMovement" DROP CONSTRAINT "InventoryMovement_variantId_fkey";
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "StockReservation" DROP CONSTRAINT "StockReservation_locationId_fkey";
ALTER TABLE "StockReservation" ADD CONSTRAINT "StockReservation_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "InventoryLocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "StockReservation" DROP CONSTRAINT "StockReservation_variantId_fkey";
ALTER TABLE "StockReservation" ADD CONSTRAINT "StockReservation_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "StockReservation" DROP CONSTRAINT "StockReservation_orderId_fkey";
ALTER TABLE "StockReservation" ADD CONSTRAINT "StockReservation_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "StockReservation" DROP CONSTRAINT "StockReservation_orderItemId_fkey";
ALTER TABLE "StockReservation" ADD CONSTRAINT "StockReservation_orderItemId_fkey" FOREIGN KEY ("orderItemId") REFERENCES "OrderItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ReservationAllocation" DROP CONSTRAINT "ReservationAllocation_reservationId_fkey";
ALTER TABLE "ReservationAllocation" ADD CONSTRAINT "ReservationAllocation_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "StockReservation" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PreorderCommitment" DROP CONSTRAINT "PreorderCommitment_locationId_fkey";
ALTER TABLE "PreorderCommitment" ADD CONSTRAINT "PreorderCommitment_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "InventoryLocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PreorderCommitment" DROP CONSTRAINT "PreorderCommitment_variantId_fkey";
ALTER TABLE "PreorderCommitment" ADD CONSTRAINT "PreorderCommitment_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PreorderCommitment" DROP CONSTRAINT "PreorderCommitment_orderId_fkey";
ALTER TABLE "PreorderCommitment" ADD CONSTRAINT "PreorderCommitment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PreorderCommitment" DROP CONSTRAINT "PreorderCommitment_orderItemId_fkey";
ALTER TABLE "PreorderCommitment" ADD CONSTRAINT "PreorderCommitment_orderItemId_fkey" FOREIGN KEY ("orderItemId") REFERENCES "OrderItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PreorderAllocation" DROP CONSTRAINT "PreorderAllocation_preorderCommitmentId_fkey";
ALTER TABLE "PreorderAllocation" ADD CONSTRAINT "PreorderAllocation_preorderCommitmentId_fkey" FOREIGN KEY ("preorderCommitmentId") REFERENCES "PreorderCommitment" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "StockAdjustmentReason" DROP CONSTRAINT "StockAdjustmentReason_businessId_fkey";
ALTER TABLE "StockAdjustmentReason" ADD CONSTRAINT "StockAdjustmentReason_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "StockAdjustment" DROP CONSTRAINT "StockAdjustment_businessId_fkey";
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "StockAdjustment" DROP CONSTRAINT "StockAdjustment_locationId_fkey";
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "InventoryLocation" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "StockAdjustment" DROP CONSTRAINT "StockAdjustment_variantId_fkey";
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Customer" DROP CONSTRAINT "Customer_businessId_fkey";
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CustomerAddress" DROP CONSTRAINT "CustomerAddress_customerId_fkey";
ALTER TABLE "CustomerAddress" ADD CONSTRAINT "CustomerAddress_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CustomerNote" DROP CONSTRAINT "CustomerNote_customerId_fkey";
ALTER TABLE "CustomerNote" ADD CONSTRAINT "CustomerNote_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "AccountClaimRequest" DROP CONSTRAINT "AccountClaimRequest_customerId_fkey";
ALTER TABLE "AccountClaimRequest" ADD CONSTRAINT "AccountClaimRequest_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Order" DROP CONSTRAINT "Order_businessId_fkey";
ALTER TABLE "Order" ADD CONSTRAINT "Order_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OrderItem" DROP CONSTRAINT "OrderItem_orderId_fkey";
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OrderAdjustment" DROP CONSTRAINT "OrderAdjustment_orderId_fkey";
ALTER TABLE "OrderAdjustment" ADD CONSTRAINT "OrderAdjustment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OrderAddress" DROP CONSTRAINT "OrderAddress_orderId_fkey";
ALTER TABLE "OrderAddress" ADD CONSTRAINT "OrderAddress_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OrderStatusHistory" DROP CONSTRAINT "OrderStatusHistory_orderId_fkey";
ALTER TABLE "OrderStatusHistory" ADD CONSTRAINT "OrderStatusHistory_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Payment" DROP CONSTRAINT "Payment_businessId_fkey";
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Payment" DROP CONSTRAINT "Payment_orderId_fkey";
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PaymentAttempt" DROP CONSTRAINT "PaymentAttempt_orderId_fkey";
ALTER TABLE "PaymentAttempt" ADD CONSTRAINT "PaymentAttempt_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PaymentAllocation" DROP CONSTRAINT "PaymentAllocation_paymentId_fkey";
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Refund" DROP CONSTRAINT "Refund_businessId_fkey";
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "RefundAttempt" DROP CONSTRAINT "RefundAttempt_refundId_fkey";
ALTER TABLE "RefundAttempt" ADD CONSTRAINT "RefundAttempt_refundId_fkey" FOREIGN KEY ("refundId") REFERENCES "Refund" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CodCollection" DROP CONSTRAINT "CodCollection_businessId_fkey";
ALTER TABLE "CodCollection" ADD CONSTRAINT "CodCollection_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CodCollection" DROP CONSTRAINT "CodCollection_orderId_fkey";
ALTER TABLE "CodCollection" ADD CONSTRAINT "CodCollection_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PaymentReconciliation" DROP CONSTRAINT "PaymentReconciliation_businessId_fkey";
ALTER TABLE "PaymentReconciliation" ADD CONSTRAINT "PaymentReconciliation_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CourierProvider" DROP CONSTRAINT "CourierProvider_businessId_fkey";
ALTER TABLE "CourierProvider" ADD CONSTRAINT "CourierProvider_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Shipment" DROP CONSTRAINT "Shipment_businessId_fkey";
ALTER TABLE "Shipment" ADD CONSTRAINT "Shipment_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ShipmentStatusHistory" DROP CONSTRAINT "ShipmentStatusHistory_shipmentId_fkey";
ALTER TABLE "ShipmentStatusHistory" ADD CONSTRAINT "ShipmentStatusHistory_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CourierCharge" DROP CONSTRAINT "CourierCharge_shipmentId_fkey";
ALTER TABLE "CourierCharge" ADD CONSTRAINT "CourierCharge_shipmentId_fkey" FOREIGN KEY ("shipmentId") REFERENCES "Shipment" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CourierSettlement" DROP CONSTRAINT "CourierSettlement_businessId_fkey";
ALTER TABLE "CourierSettlement" ADD CONSTRAINT "CourierSettlement_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "CourierSettlementEntry" DROP CONSTRAINT "CourierSettlementEntry_settlementId_fkey";
ALTER TABLE "CourierSettlementEntry" ADD CONSTRAINT "CourierSettlementEntry_settlementId_fkey" FOREIGN KEY ("settlementId") REFERENCES "CourierSettlement" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ExchangeRequest" DROP CONSTRAINT "ExchangeRequest_businessId_fkey";
ALTER TABLE "ExchangeRequest" ADD CONSTRAINT "ExchangeRequest_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ExchangeRequest" DROP CONSTRAINT "ExchangeRequest_orderId_fkey";
ALTER TABLE "ExchangeRequest" ADD CONSTRAINT "ExchangeRequest_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ExchangeItem" DROP CONSTRAINT "ExchangeItem_exchangeRequestId_fkey";
ALTER TABLE "ExchangeItem" ADD CONSTRAINT "ExchangeItem_exchangeRequestId_fkey" FOREIGN KEY ("exchangeRequestId") REFERENCES "ExchangeRequest" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ExchangeStatusHistory" DROP CONSTRAINT "ExchangeStatusHistory_exchangeRequestId_fkey";
ALTER TABLE "ExchangeStatusHistory" ADD CONSTRAINT "ExchangeStatusHistory_exchangeRequestId_fkey" FOREIGN KEY ("exchangeRequestId") REFERENCES "ExchangeRequest" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Reseller" DROP CONSTRAINT "Reseller_businessId_fkey";
ALTER TABLE "Reseller" ADD CONSTRAINT "Reseller_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerLedgerEntry" DROP CONSTRAINT "ResellerLedgerEntry_businessId_fkey";
ALTER TABLE "ResellerLedgerEntry" ADD CONSTRAINT "ResellerLedgerEntry_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerLedgerEntry" DROP CONSTRAINT "ResellerLedgerEntry_resellerId_fkey";
ALTER TABLE "ResellerLedgerEntry" ADD CONSTRAINT "ResellerLedgerEntry_resellerId_fkey" FOREIGN KEY ("resellerId") REFERENCES "Reseller" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerOrderEarning" DROP CONSTRAINT "ResellerOrderEarning_businessId_fkey";
ALTER TABLE "ResellerOrderEarning" ADD CONSTRAINT "ResellerOrderEarning_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerOrderEarning" DROP CONSTRAINT "ResellerOrderEarning_resellerId_fkey";
ALTER TABLE "ResellerOrderEarning" ADD CONSTRAINT "ResellerOrderEarning_resellerId_fkey" FOREIGN KEY ("resellerId") REFERENCES "Reseller" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerOrderEarning" DROP CONSTRAINT "ResellerOrderEarning_orderId_fkey";
ALTER TABLE "ResellerOrderEarning" ADD CONSTRAINT "ResellerOrderEarning_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerCollectionChange" DROP CONSTRAINT "ResellerCollectionChange_orderId_fkey";
ALTER TABLE "ResellerCollectionChange" ADD CONSTRAINT "ResellerCollectionChange_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerCollectionChange" DROP CONSTRAINT "ResellerCollectionChange_resellerId_fkey";
ALTER TABLE "ResellerCollectionChange" ADD CONSTRAINT "ResellerCollectionChange_resellerId_fkey" FOREIGN KEY ("resellerId") REFERENCES "Reseller" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerPayout" DROP CONSTRAINT "ResellerPayout_businessId_fkey";
ALTER TABLE "ResellerPayout" ADD CONSTRAINT "ResellerPayout_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerPayout" DROP CONSTRAINT "ResellerPayout_resellerId_fkey";
ALTER TABLE "ResellerPayout" ADD CONSTRAINT "ResellerPayout_resellerId_fkey" FOREIGN KEY ("resellerId") REFERENCES "Reseller" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ResellerPayoutEntry" DROP CONSTRAINT "ResellerPayoutEntry_payoutId_fkey";
ALTER TABLE "ResellerPayoutEntry" ADD CONSTRAINT "ResellerPayoutEntry_payoutId_fkey" FOREIGN KEY ("payoutId") REFERENCES "ResellerPayout" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ResellerPayoutEntry" DROP CONSTRAINT "ResellerPayoutEntry_ledgerEntryId_fkey";
ALTER TABLE "ResellerPayoutEntry" ADD CONSTRAINT "ResellerPayoutEntry_ledgerEntryId_fkey" FOREIGN KEY ("ledgerEntryId") REFERENCES "ResellerLedgerEntry" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ResellerPayoutTransaction" DROP CONSTRAINT "ResellerPayoutTransaction_payoutId_fkey";
ALTER TABLE "ResellerPayoutTransaction" ADD CONSTRAINT "ResellerPayoutTransaction_payoutId_fkey" FOREIGN KEY ("payoutId") REFERENCES "ResellerPayout" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MediaFolder" DROP CONSTRAINT "MediaFolder_businessId_fkey";
ALTER TABLE "MediaFolder" ADD CONSTRAINT "MediaFolder_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MediaAsset" DROP CONSTRAINT "MediaAsset_businessId_fkey";
ALTER TABLE "MediaAsset" ADD CONSTRAINT "MediaAsset_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MediaUsage" DROP CONSTRAINT "MediaUsage_mediaId_fkey";
ALTER TABLE "MediaUsage" ADD CONSTRAINT "MediaUsage_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "MediaAsset" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MediaUsage" DROP CONSTRAINT "MediaUsage_productId_fkey";
ALTER TABLE "MediaUsage" ADD CONSTRAINT "MediaUsage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MediaUsage" DROP CONSTRAINT "MediaUsage_variantId_fkey";
ALTER TABLE "MediaUsage" ADD CONSTRAINT "MediaUsage_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Page" DROP CONSTRAINT "Page_businessId_fkey";
ALTER TABLE "Page" ADD CONSTRAINT "Page_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Page" DROP CONSTRAINT "Page_storefrontId_fkey";
ALTER TABLE "Page" ADD CONSTRAINT "Page_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "PageVersion" DROP CONSTRAINT "PageVersion_pageId_fkey";
ALTER TABLE "PageVersion" ADD CONSTRAINT "PageVersion_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NavigationMenu" DROP CONSTRAINT "NavigationMenu_storefrontId_fkey";
ALTER TABLE "NavigationMenu" ADD CONSTRAINT "NavigationMenu_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NavigationMenuItem" DROP CONSTRAINT "NavigationMenuItem_menuId_fkey";
ALTER TABLE "NavigationMenuItem" ADD CONSTRAINT "NavigationMenuItem_menuId_fkey" FOREIGN KEY ("menuId") REFERENCES "NavigationMenu" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Review" DROP CONSTRAINT "Review_businessId_fkey";
ALTER TABLE "Review" ADD CONSTRAINT "Review_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Review" DROP CONSTRAINT "Review_productId_fkey";
ALTER TABLE "Review" ADD CONSTRAINT "Review_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Review" DROP CONSTRAINT "Review_customerId_fkey";
ALTER TABLE "Review" ADD CONSTRAINT "Review_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ReviewImage" DROP CONSTRAINT "ReviewImage_reviewId_fkey";
ALTER TABLE "ReviewImage" ADD CONSTRAINT "ReviewImage_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "Review" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ReviewImage" DROP CONSTRAINT "ReviewImage_mediaId_fkey";
ALTER TABLE "ReviewImage" ADD CONSTRAINT "ReviewImage_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "MediaAsset" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ReviewReport" DROP CONSTRAINT "ReviewReport_reviewId_fkey";
ALTER TABLE "ReviewReport" ADD CONSTRAINT "ReviewReport_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "Review" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Integration" DROP CONSTRAINT "Integration_businessId_fkey";
ALTER TABLE "Integration" ADD CONSTRAINT "Integration_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Integration" DROP CONSTRAINT "Integration_storefrontId_fkey";
ALTER TABLE "Integration" ADD CONSTRAINT "Integration_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "IntegrationSecret" DROP CONSTRAINT "IntegrationSecret_integrationId_fkey";
ALTER TABLE "IntegrationSecret" ADD CONSTRAINT "IntegrationSecret_integrationId_fkey" FOREIGN KEY ("integrationId") REFERENCES "Integration" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ApiKey" DROP CONSTRAINT "ApiKey_businessId_fkey";
ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ApiKeyScope" DROP CONSTRAINT "ApiKeyScope_apiKeyId_fkey";
ALTER TABLE "ApiKeyScope" ADD CONSTRAINT "ApiKeyScope_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "ApiKey" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MarketingIntegration" DROP CONSTRAINT "MarketingIntegration_businessId_fkey";
ALTER TABLE "MarketingIntegration" ADD CONSTRAINT "MarketingIntegration_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MarketingIntegration" DROP CONSTRAINT "MarketingIntegration_storefrontId_fkey";
ALTER TABLE "MarketingIntegration" ADD CONSTRAINT "MarketingIntegration_storefrontId_fkey" FOREIGN KEY ("storefrontId") REFERENCES "Storefront" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MarketingEvent" DROP CONSTRAINT "MarketingEvent_businessId_fkey";
ALTER TABLE "MarketingEvent" ADD CONSTRAINT "MarketingEvent_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MarketingEvent" DROP CONSTRAINT "MarketingEvent_marketingIntegrationId_fkey";
ALTER TABLE "MarketingEvent" ADD CONSTRAINT "MarketingEvent_marketingIntegrationId_fkey" FOREIGN KEY ("marketingIntegrationId") REFERENCES "MarketingIntegration" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Plugin" DROP CONSTRAINT "Plugin_businessId_fkey";
ALTER TABLE "Plugin" ADD CONSTRAINT "Plugin_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "WebhookSubscription" DROP CONSTRAINT "WebhookSubscription_businessId_fkey";
ALTER TABLE "WebhookSubscription" ADD CONSTRAINT "WebhookSubscription_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "WebhookDelivery" DROP CONSTRAINT "WebhookDelivery_subscriptionId_fkey";
ALTER TABLE "WebhookDelivery" ADD CONSTRAINT "WebhookDelivery_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "WebhookSubscription" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Notification" DROP CONSTRAINT "Notification_businessId_fkey";
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NotificationRecipient" DROP CONSTRAINT "NotificationRecipient_notificationId_fkey";
ALTER TABLE "NotificationRecipient" ADD CONSTRAINT "NotificationRecipient_notificationId_fkey" FOREIGN KEY ("notificationId") REFERENCES "Notification" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NotificationRecipient" DROP CONSTRAINT "NotificationRecipient_userId_fkey";
ALTER TABLE "NotificationRecipient" ADD CONSTRAINT "NotificationRecipient_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NotificationPreference" DROP CONSTRAINT "NotificationPreference_userId_fkey";
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "AuditLog" DROP CONSTRAINT "AuditLog_businessId_fkey";
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "BackgroundJob" DROP CONSTRAINT "BackgroundJob_businessId_fkey";
ALTER TABLE "BackgroundJob" ADD CONSTRAINT "BackgroundJob_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OutboxEvent" DROP CONSTRAINT "OutboxEvent_businessId_fkey";
ALTER TABLE "OutboxEvent" ADD CONSTRAINT "OutboxEvent_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
